version: "3"

services:

  py3:
    build:
      context: .
      dockerfile: Dockerfile.py3
    command: py.test -s --cov=arrested --cov-report=term-missing --tb=short tests/
    volumes:
      - .:/opt/code
    tty: true
    stdin_open: true

  api:
    build:
      context: example/
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
    volumes:
      - .:/opt/code

  e2e_tests:
    build:
      context: .
      dockerfile: Dockerfile.py3
    command: behave tests/e2e_tests/features
    volumes:
      - .:/opt/code
    environment:
      - SERVER_URL=http://api:5000
    tty: true
    stdin_open: true
